### ISSUE TITLE
Require breaks on loading lazy.node.js using jerk

### ISSUE THREAD

**Issue by bichotll** [dtao/lazy.js#144]
The script just requires lazy as the proper way:

```
require("lazy.js")
```

If I load the file lazy.js it does not give any problem. But it breaks when it tries to require the file lazy.node.js on line 19:

```
StreamedSequence.prototype = new Lazy.StreamLikeSequence();
```

Is there any option to load the browser one and make a workaround?

The error:

```
● MapRow › it encountered a declaration exception
  - TypeError: /var/www/test/test-react-map-radar/node_modules/lazy.js/lazy.node.js: undefined is not a function
        at /var/www/test/test-react-map-radar/node_modules/lazy.js/lazy.node.js:19:30
        at Object.runContentWithLocalBindings (/var/www/test/test-react-map-radar/node_modules/gulp-jest/node_modules/jest-cli/src/lib/utils.js:315:17)
        at Loader._execModule (/var/www/test/test-react-map-radar/node_modules/gulp-jest/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:243:9)
        at Loader.requireModule (/var/www/test/test-react-map-radar/node_modules/gulp-jest/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:886:12)
        at Loader.requireModuleOrMock (/var/www/test/test-react-map-radar/node_modules/gulp-jest/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:907:17)
        at Suite.<anonymous> (/var/www/test/test-react-map-radar/app/scripts/ui/__tests__/MapTable-test.js:7:13)
        at env.describe_ (<anonymous>:40:25)
        at env.describe (<anonymous>:27:19)
        at /var/www/test/test-react-map-radar/app/scripts/ui/__tests__/MapTable-test.js:5:1
        at Object.runContentWithLocalBindings (/var/www/test/test-react-map-radar/node_modules/gulp-jest/node_modules/jest-cli/src/lib/utils.js:315:17)
        at Loader._execModule (/var/www/test/test-react-map-radar/node_modules/gulp-jest/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:243:9)
        at Loader.requireModule (/var/www/test/test-react-map-radar/node_modules/gulp-jest/node_modules/jest-cli/src/HasteModuleLoader/HasteModuleLoader.js:886:12)
        at jasmineTestRunner (/var/www/test/test-react-map-radar/node_modules/gulp-jest/node_modules/jest-cli/src/jasmineTestRunner/jasmineTestRunner.js:225:16)
        at /var/www/test/test-react-map-radar/node_modules/gulp-jest/node_modules/jest-cli/src/TestRunner.js:370:12
        at /var/www/test/test-react-map-radar/node_modules/gulp-jest/node_modules/jest-cli/src/lib/FakeTimers.js:259:7
        at process._tickCallback (node.js:419:13)
1 test failed, 1 test passed (2 total)
```

**Comment by dtao** [comment]
Jerk? Do you mean [Jest](https://facebook.github.io/jest/)? I'm not sure how to reproduce this.

**Comment by dtao** [comment]
I ran a very minimal test using Jest and it seemed to work. Without any additional details, I'm not sure what to do with this issue; so I'm going to close it. If you are still experiencing issues let me know and we can either re-open this or create a new issue.
