### ISSUE TITLE
stream.setEncoding(this.encoding || 'utf8');

### ISSUE THREAD

**Issue by miguelmota** [dtao/lazy.js#160]
``` bash
$ node -v
v2.4.0

$ node index.js
/Users/moogs/Documents/app/node_modules/lazy.js/lazy.node.js:40
      stream.setEncoding(this.encoding || 'utf8');
                             ^
TypeError: Cannot read property 'encoding' of undefined
    at /Users/moogs/Documents/app/node_modules/lazy.js/lazy.node.js:40:30
    at Sequence.FileStreamSequence.openStream (/Users/moogs/Documents/app/node_modules/l
azy.js/lazy.node.js:83:3)
    at Sequence.StreamedSequence.each (/Users/moogs/Documents/app/node_modules/lazy.js/l
azy.node.js:38:8)
    at Sequence.each (/Users/moogs/Documents/app/node_modules/lazy.js/lazy.js:5513:30)
    at Sequence.each (/Users/moogs/Documents/app/node_modules/lazy.js/lazy.js:1023:30)
    at Object.<anonymous> (/Users/moogs/Documents/app/read_csv.js:6:4)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

index.js

``` javascript
const Lazy = require('lazy.js');

Lazy.readFile(__dirname + '/test.txt')
  .lines()
  .take(5)
  .each(process);

function process(data) {
  console.log(data);
}
```

test.txt

```
hello
```

**Comment by dtao** [comment]
Wow, what a dumb mistake on my part! I will fix with a test.

**Comment by dtao** [comment]
Hmm, so this was a dumb mistake on my part, but it was also a bit sneaky of you to include a trace from a completely different file (read_csv.js?) than your example...

If you try running your example, it works. Maybe you could include the code that actually fails?
